services:
  dump1090:
    image: dump1090-image
    container_name: dump1090-fa
    hostname: dump1090-fa
    restart: on-failure:3
    environment:
      - LAT=37.91342     # NOTE: Replace with your actual latitude
      - LON=-122.05898   # NOTE: Replace with your actual longitude
    ports:
      - "8080:8080"      # Web interface for live map (lighttpd)
      - "30001:30001"    # RAW Beast input: Raw binary input from external sources (rarely used unless feeding from another decoder)
      - "30002:30002"    # RAW Beast output: Raw binary ADS-B output (Beast format) for external consumers (e.g. FR24, RBFeeder, other tools)
      - "30003:30003"    # SBS output (TCP): Human-readable ADS-B output in SBS-1 format (text-based, e.g. used by Virtual Radar Server)
      - "30005:30005"    # RAW Beast output (for PiAware): Main output port used by feeders like PiAware, FR24, etc. for MLAT and ADS-B data
    devices:
      - "/dev/bus/usb:/dev/bus/usb"  # Pass USB device for RTL-SDR
    privileged: true                 # ensures USB access across systems
    networks:
      - adsb-net

  tar1090:
    image: ghcr.io/sdr-enthusiasts/docker-tar1090:latest
    container_name: tar1090
    hostname: tar1090
    restart: on-failure:3
    environment:
      - TZ=America/Los_Angeles
      - BEASTHOST=dump1090-fa
      - BEASTPORT=30005
      - LAT=37.91342     # NOTE: Replace with your actual latitude
      - LONG=-122.05898  # NOTE: Replace with your actual longitude
    ports:
      - "8078:80"  # Web interface for tar1090
    volumes:
      - tar1090-globe-history:/var/globe_history
      - tar1090-timelapse1090:/var/timelapse1090
      - tar1090-graphs1090:/var/lib/collectd
    tmpfs:
      - /run:exec,size=64M
      - /var/log
    networks:
      - adsb-net

  piaware:
    image: piaware-image
    container_name: piaware
    hostname: piaware
    restart: on-failure:3
    volumes:
      - ./piaware.conf:/etc/piaware.conf
    healthcheck:
      test: ["CMD", "pgrep", "piaware"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - dump1090
    networks:
      - adsb-net

volumes:
  tar1090-globe-history:
  tar1090-timelapse1090:
  tar1090-graphs1090:

networks:
  adsb-net:
    driver: bridge
